#!/usr/bin/env node
// RESTATES: nothing. This tool carries no rule of its own — it copies the book's templates into the
// plugin so a partner has them, and the argument for each template stays in the template.
//
// The shapes every repository writes to, carried where a partner can reach them.
//
//   node templates-export.ts <book>            check: is every copy current?  (exit 1 if not)
//   node templates-export.ts <book> --write    copy the book's templates over
//
// WHY THIS EXISTS. A partner installs the marketplace and the libraries. They never get
// `spn-foundation/docs`, so until this ran, a partner opening their first workstream had **no
// approach template at all** — and no construct seat, no page template, nothing. Their agent would
// invent a shape, and the invention would become that partner's convention. The one moment it
// matters most is the moment they have least: a new repository whose own `docs/` is the thing they
// are about to write.
//
// THE COPY IS BYTE-IDENTICAL AND THAT IS DELIBERATE. Nothing is stamped INSIDE a template, because
// these are five file types — `.html`, `.md`, `.py`, `.sql` — and a header in each would be four
// comment syntaxes and four ways to corrupt a file somebody copies verbatim. The stamps live in one
// `README.md` beside them, which `restate-drift` already knows how to read.
//
// THE BOOK OWNS THEM. A builder edits the template in the book; this copies it; the plugin release
// carries it to every partner. Editing a copy here is editing an output.

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

import { seenHash, treeHash } from "../lib/restates.ts";

/** Where the book keeps them. One folder, four groups, and the groups are the book's own. */
const BOOK_TEMPLATES = "docs/04-capabilities/01-devex/04-workspace/04-docs/templates";

const HERE = dirname(new URL(import.meta.url).pathname);
const PLUGIN = resolve(HERE, "..", "..");
const OUT = join(PLUGIN, "templates");
const INDEX = join(OUT, "README.md");
/** The book's own generated index, beside the templates it lists. */
const BOOK_INDEX = "index.md";

/** Every file under the book's templates folder, as `<group>/<name>`. */
function templatesOf(book: string): string[] {
  const root = join(book, BOOK_TEMPLATES);
  if (!existsSync(root)) return [];
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir).sort()) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) walk(full);
      else out.push(relative(root, full));
    }
  };
  walk(root);
  return out;
}

/** The BOOK's own index of its templates — a file, so an ordinary citation can watch it. */
function renderBookIndex(book: string, names: string[]): string {
  const rows = names.map((name) =>
    `| \`${name}\` | \`${seenHash(readFileSync(join(book, BOOK_TEMPLATES, name), "utf8"))}\` |`);
  return [
    "# The templates this book owns",
    "",
    "**Generated by `templates-export.ts`. Do not hand-edit.** One row per template, each carrying the",
    "hash of that file's contents.",
    "",
    "**This file exists so that ADDING a template is a change somebody can see.** The plugins ship a",
    "copy of this folder for partners, who never get the book. A citation per template would report an",
    "edit to any of them and say nothing at all about a new one — a template nobody cited has nothing",
    "to compare against, and *the book grew a shape a partner does not have* is the failure the copy",
    "exists to prevent. The plugin restates **this index**, so a template added, removed, renamed or",
    "edited all move the same one hash.",
    "",
    "| Template | Hash |",
    "| --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

/**
 * The index the drift check reads — ONE citation, naming the FOLDER (`RD.DOCS.091`).
 *
 * A STAMP PER FILE MISSES THE THING MOST WORTH CATCHING. Seventeen citations report an edit to any
 * of the seventeen and say nothing about an eighteenth, because a file nobody cited has nothing to
 * compare against — and *the book grew a shape a partner does not have* is precisely what this copy
 * exists to prevent.
 *
 * A BOOK-SIDE INDEX FILE WAS TRIED FIRST AND IS WEAKER. Citing a generated index the ordinary way
 * needs no new grammar, but the index itself only moves when this tool runs — so adding a template
 * and not running the export leaves `restate-drift` silent, which is the exact hole being closed.
 * Proven both ways on 2026-09-24. The index is still written, because it is a readable list of what
 * the book holds; the STAMP is the folder.
 */
function renderIndex(book: string, names: string[]): string {
  const chapters = [{ path: BOOK_TEMPLATES, seen: treeHash(join(book, BOOK_TEMPLATES)) }];
  const groups = new Map<string, string[]>();
  for (const name of names) {
    const [group, file] = name.split("/");
    groups.set(group, [...(groups.get(group) ?? []), file]);
  }
  const rows = [...groups].map(([group, files]) =>
    `| \`${group}/\` | ${files.map((f) => `[\`${f}\`](${group}/${f})`).join(" · ")} |`);
  return [
    "<!-- spn:restates",
    JSON.stringify({ chapters }, null, 2),
    "-->",
    "# The templates, as a partner has them",
    "",
    "**The book owns every file here and this folder is a copy.** They are byte-identical to",
    "`spn-foundation/docs/04-capabilities/01-devex/04-workspace/04-docs/templates/`, and when the two",
    "disagree the book wins. `templates-export.ts` writes them and `restate-drift` reports a copy that",
    "has fallen behind, so a builder's edit reaches every partner with the next plugin release rather",
    "than being discovered by somebody's first session going wrong.",
    "",
    "**The stamp above names the folder, not each file** (`RD.DOCS.091`). One citation per template",
    "would report every edit and miss every addition — a template nobody cited has nothing to compare",
    "against, and *the book grew a shape a partner does not have* is what this copy exists to prevent.",
    "A folder hash covers added, removed, renamed and edited at once.",
    "",
    "**They are here because the plugins ship without the book beside them.** A partner installs the",
    "marketplace and the libraries and never gets `docs/`. The moment that costs most is the first one:",
    "a new repository whose own documentation is the thing they are about to write, with nothing on",
    "disk to copy from.",
    "",
    "**Copy a template rather than writing a page from memory.** Each carries the section order, the",
    "card shape and the furniture every check reads, and a page assembled by hand is one that passes a",
    "review and fails a gate.",
    "",
    "| Group | Templates |",
    "| --- | --- |",
    ...rows,
    "",
    "**Never edit a file here.** It is an output. The rule lives in the book's copy, a builder changes",
    "it there, and the export carries it.",
    "",
  ].join("\n");
}

const book = process.argv[2] && !process.argv[2].startsWith("--") ? resolve(process.argv[2]) : "";
const write = process.argv.includes("--write");

if (!book || !existsSync(join(book, BOOK_TEMPLATES))) {
  // A PARTNER RUNS THIS AND NOTHING HAPPENS, which is correct. They hold the plugin and not the
  // book, so there is nothing to export from — the copies they already have are the answer.
  console.log("no foundation book here — nothing to export, and the shipped copies stand");
  process.exit(0);
}

const names = templatesOf(book).filter((name) => name !== BOOK_INDEX);
// The book's index is written FIRST, because it is one of the files the copy carries.
const bookIndex = renderBookIndex(book, names);
const bookIndexPath = join(book, BOOK_TEMPLATES, BOOK_INDEX);
const bookIndexStale = !existsSync(bookIndexPath) || readFileSync(bookIndexPath, "utf8") !== bookIndex;
if (bookIndexStale && write) writeFileSync(bookIndexPath, bookIndex);
const stale: string[] = [];
for (const name of names) {
  const from = join(book, BOOK_TEMPLATES, name);
  const to = join(OUT, name);
  const source = readFileSync(from);
  const current = existsSync(to) ? readFileSync(to) : null;
  if (current !== null && current.equals(source)) continue;
  stale.push(name);
  if (write) {
    mkdirSync(dirname(to), { recursive: true });
    writeFileSync(to, source);
  }
}

const index = renderIndex(book, names);
const indexStale = !existsSync(INDEX) || readFileSync(INDEX, "utf8") !== index;
if (indexStale && write) {
  mkdirSync(OUT, { recursive: true });
  writeFileSync(INDEX, index);
}

if (write) {
  console.log(`${names.length} template(s) exported · ${stale.length} rewritten · index ${indexStale ? "rewritten" : "current"}`);
  process.exit(0);
}

if (!stale.length && !indexStale && !bookIndexStale) {
  console.log(`${names.length} template(s) · every copy current`);
  process.exit(0);
}
console.log(`${stale.length} template(s) behind the book${indexStale ? ", and the index too" : ""}:`);
for (const name of stale) console.log(`  ${name}`);
console.log("  run `templates-export.ts <book> --write`");
process.exit(1);
