#!/usr/bin/env bash
# spn-core PreToolUse guard: deny edits to files generated by spnutils.
#
# Detection (conservative — when unsure, allow):
#   1. Path matches  */src/contract/validators/*.ts   (gen-validators output)
#   2. Path matches  */dist/generated/*               (build-time generated output)
#   3. The file exists and its first 3 lines contain "Generated by spnutils"
#
# Write and Edit name their file in tool_input.file_path. Bash does not — it carries a command,
# and the path is inside it. This script read only file_path and exited when it was empty, so
# every generated file was rewritable through a heredoc, a `sed -i` or a `cp` even though the
# matcher covered Bash (the arc docs-voice, finding 35 — finding 34 is the same defect in
# doc-check.py). The write routes are parsed in ONE place, `doc-check.py --bash-writes`, so a
# newly learned route serves both hooks at once.
#
# On deny: print the documented PreToolUse JSON decision and exit 0.
# On anything unexpected (no jq, unparsable input, no file path): exit 0 silently — allow.

# Without jq we cannot parse the event safely — allow.
command -v jq >/dev/null 2>&1 || exit 0

INPUT=$(cat 2>/dev/null) || exit 0
[ -n "$INPUT" ] || exit 0

deny() {
  jq -n --arg reason "$1" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: $reason
    }
  }'
  exit 0
}

REGEN_HINT="This file is generated — hand edits are lost on the next generator run. Edit the source instead and regenerate: contract validators come from contract/states/** via 'spnutils apps gen-validators -p <pkg>'; package barrels via 'spnutils apps gen-barrel -p <pkg>'; client SDKs regenerate from the running service's published API document. Never hand-edit generated output."

# One path. Denies and exits, or returns so the next path is tried.
check_one() {
  FILE_PATH="$1"
  [ -n "$FILE_PATH" ] || return 0

  case "$FILE_PATH" in
    */src/contract/validators/*.ts)
      deny "Denied: $FILE_PATH is a generated Zod validator (spnutils apps gen-validators). $REGEN_HINT"
      ;;
    */dist/generated/*)
      deny "Denied: $FILE_PATH is generated build output. $REGEN_HINT"
      ;;
  esac

  # Content check — only for files that already exist and are readable. A shell write to a path
  # that does not exist yet is judged on its path alone, which the two cases above already do.
  if [ -f "$FILE_PATH" ] && [ -r "$FILE_PATH" ]; then
    if head -n 3 "$FILE_PATH" 2>/dev/null | grep -q "Generated by spnutils"; then
      deny "Denied: $FILE_PATH declares 'Generated by spnutils' in its header. $REGEN_HINT"
    fi
  fi
  return 0
}

FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || exit 0

if [ -n "$FILE_PATH" ]; then
  check_one "$FILE_PATH"
else
  # A Bash call. Ask the shared parser which paths this command writes, and judge each one.
  # If python3 or the parser is missing we allow, exactly as a missing jq allows.
  command -v python3 >/dev/null 2>&1 || exit 0
  PARSER="$(dirname "$0")/doc-check.py"
  [ -r "$PARSER" ] || exit 0
  TARGETS=$(printf '%s' "$INPUT" | python3 "$PARSER" --bash-writes 2>/dev/null) || exit 0
  while IFS= read -r target; do
    [ -n "$target" ] && check_one "$target"
  done <<EOF
$TARGETS
EOF
fi

# No match — no decision; normal permission flow applies.
exit 0
