#!/usr/bin/env bash
# spn-core PreToolUse guard: deny Write/Edit on files generated by spnutils.
#
# Detection (conservative — when unsure, allow):
#   1. Path matches  */src/contract/validators/*.ts   (gen-validators output)
#   2. Path matches  */dist/generated/*               (build-time generated output)
#   3. The file exists and its first 3 lines contain "Generated by spnutils"
#
# On deny: print the documented PreToolUse JSON decision and exit 0.
# On anything unexpected (no jq, unparsable input, no file path): exit 0 silently — allow.

# Without jq we cannot parse the event safely — allow.
command -v jq >/dev/null 2>&1 || exit 0

INPUT=$(cat 2>/dev/null) || exit 0
[ -n "$INPUT" ] || exit 0

FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || exit 0
[ -n "$FILE_PATH" ] || exit 0

deny() {
  jq -n --arg reason "$1" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: $reason
    }
  }'
  exit 0
}

REGEN_HINT="This file is generated — hand edits are lost on the next generator run. Edit the source instead and regenerate: contract validators come from contract/states/** via 'spnutils apps gen-validators -p <pkg>'; package barrels via 'spnutils apps gen-barrel -p <pkg>'; client SDKs regenerate from the running service's published API document. Never hand-edit generated output."

case "$FILE_PATH" in
  */src/contract/validators/*.ts)
    deny "Denied: $FILE_PATH is a generated Zod validator (spnutils apps gen-validators). $REGEN_HINT"
    ;;
  */dist/generated/*)
    deny "Denied: $FILE_PATH is generated build output. $REGEN_HINT"
    ;;
esac

# Content check — only for files that already exist and are readable.
if [ -f "$FILE_PATH" ] && [ -r "$FILE_PATH" ]; then
  if head -n 3 "$FILE_PATH" 2>/dev/null | grep -q "Generated by spnutils"; then
    deny "Denied: $FILE_PATH declares 'Generated by spnutils' in its header. $REGEN_HINT"
  fi
fi

# No match — no decision; normal permission flow applies.
exit 0
