// RESTATES: nothing. This carries no rule of its own — it copies the book's templates into the
// plugin so a partner has them, and the argument for each template stays in the template.
//
// The `files`-kind restatement: the shapes every repository writes to, carried where a partner can
// reach them.
//
//     spn-devex restates files check <book>     is every copy current?  (exit 1 if not)
//     spn-devex restates files write <book>     copy the book's templates over, and remove a copy the book no longer holds
//
// A SUBJECT WITH TWO ACTIONS, EACH TAKING THE BOOK'S FOLDER. Both name it, because a `write` changes
// files in two repositories: the book's own index of its templates, and this plugin's copies.
//
// THE COPY FOLLOWS THE BOOK BOTH WAYS. A template the book deleted is a copy somebody still copies
// from, so `check` reports it as drift and `write` removes it.
//
// THE COPY IS BYTE-IDENTICAL AND THAT IS DELIBERATE. Nothing is stamped INSIDE a template, because
// these are five file types and a header in each would be four comment syntaxes and four ways to
// corrupt a file somebody copies verbatim. The stamps live in one `README.md` beside them, which
// `restates check` already knows how to read.

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

import { type Action, REQUIRED, onePath, readWords, scopeOf } from "../../../../../plugin-support-lib/src/lib/command.ts";
import { seenHash, treeHash } from "../../lib/restates.ts";
import { BOOK_TEMPLATES, PLUGIN_TEMPLATES } from "../../../../../plugin-support-lib/src/lib/docs-tree.ts";


const HERE = dirname(new URL(import.meta.url).pathname);
const PLUGIN = resolve(HERE, "..", "..", "..");
// THE COPY SITS BESIDE THE REF THAT NAMES IT. `doc-sets.md` carries the `files` citation for this
// folder, so a drift check reads one directory rather than two — the citation and the thing cited
// are siblings (RD.DEVEX.AGENT.072).
const OUT = join(PLUGIN, PLUGIN_TEMPLATES);
/** The copy's own index, which the book does not hold. */
const COPY_INDEX = "README.md";
/** The book's own generated index, beside the templates it lists. */
const BOOK_INDEX = "index.md";

/** Every file under a folder, as `<group>/<name>`. */
function filesUnder(root: string): string[] {
  if (!existsSync(root)) return [];
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir).sort()) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) walk(full);
      else out.push(relative(root, full).split("\\").join("/"));
    }
  };
  walk(root);
  return out;
}

/** Every file under the book's templates folder, as `<group>/<name>`. */
const templatesOf = (book: string): string[] => filesUnder(join(book, BOOK_TEMPLATES));

/** Removes each folder under `root` that holds nothing, deepest first. `root` itself stays. */
function removeEmptyFolders(root: string): void {
  for (const entry of readdirSync(root)) {
    const full = join(root, entry);
    if (!statSync(full).isDirectory()) continue;
    removeEmptyFolders(full);
    if (readdirSync(full).length === 0) rmSync(full, { recursive: true });
  }
}

/** The BOOK's own index of its templates — a file, so an ordinary citation can watch it. */
function renderBookIndex(book: string, names: string[]): string {
  const rows = names.map((name) =>
    `| \`${name}\` | \`${seenHash(readFileSync(join(book, BOOK_TEMPLATES, name), "utf8"))}\` |`);
  return [
    "# The templates this book owns",
    "",
    "**Generated by `restates files write`. Do not hand-edit.** One row per template, each carrying",
    "the hash of that file's contents.",
    "",
    "**This file exists so that ADDING a template is a change somebody can see.** The plugins ship a",
    "copy of this folder for partners, who never get the book. A citation per template would report an",
    "edit to any of them and say nothing at all about a new one — a template nobody cited has nothing",
    "to compare against, and *the book grew a shape a partner does not have* is the failure the copy",
    "exists to prevent. The plugin restates **this index**, so a template added, removed, renamed or",
    "edited all move the same one hash.",
    "",
    "| Template | Hash |",
    "| --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

/**
 * The index the drift check reads — ONE citation, naming the FOLDER (`RD.DEVEX.AGENT.072`).
 *
 * A STAMP PER FILE MISSES THE THING MOST WORTH CATCHING — a file nobody cited has nothing to
 * compare against, and *the book grew a shape a partner does not have* is precisely what this copy
 * exists to prevent.
 */
function renderIndex(book: string, names: string[]): string {
  // A TEMPLATE IS COPIED, NEVER REWRITTEN, so the citation kind is `files` and not `docs`
  // (RD.DEVEX.AGENT.072). A `docs` entry means the agent restates the source in its own words; a `files`
  // entry means the copy is byte-identical, which is the whole value of a template — what a
  // partner copies from is what the book ships.
  const files = [{ path: `spn-foundation/${BOOK_TEMPLATES}`, seen: treeHash(join(book, BOOK_TEMPLATES)) }];
  const groups = new Map<string, string[]>();
  for (const name of names) {
    const [group, file] = name.split("/");
    groups.set(group, [...(groups.get(group) ?? []), file]);
  }
  const rows = [...groups].map(([group, files]) =>
    `| \`${group}/\` | ${files.map((f) => `[\`${f}\`](${group}/${f})`).join(" · ")} |`);
  return [
    "<!-- spn:restates",
    JSON.stringify({ files }, null, 2),
    "-->",
    "# The templates, as a partner has them",
    "",
    "**The book owns every file here and this folder is a copy.** They are byte-identical to",
    `\`spn-foundation/${BOOK_TEMPLATES}/\`, and when the two`,
    "disagree the book wins. `restates files write` writes them and `restates check` reports a copy",
    "that has fallen behind, so a builder's edit reaches every partner with the next plugin release",
    "rather than being discovered by somebody's first session going wrong.",
    "",
    "**The stamp above names the folder, not each file** (`RD.DEVEX.AGENT.072`). One citation per template",
    "would report every edit and miss every addition — a template nobody cited has nothing to compare",
    "against, and *the book grew a shape a partner does not have* is what this copy exists to prevent.",
    "A folder hash covers added, removed, renamed and edited at once.",
    "",
    "**They are here because the plugins ship without the book beside them.** A partner installs the",
    "marketplace and the libraries and never gets `docs/`. The moment that costs most is the first one:",
    "a new repository whose own documentation is the thing they are about to write, with nothing on",
    "disk to copy from.",
    "",
    "**Copy a template rather than writing a page from memory.** Each carries the section order, the",
    "card shape and the furniture every check reads, and a page assembled by hand is one that passes a",
    "review and fails a gate.",
    "",
    "| Group | Templates |",
    "| --- | --- |",
    ...rows,
    "",
    "**Never edit a file here.** It is an output. The rule lives in the book's copy, a builder changes",
    "it there, and the export carries it.",
    "",
  ].join("\n");
}

export const describe = "the `files`-kind restatement — copy the book's templates into this plugin's refs";

/**
 * The export, or its check, over one book and one copy folder.
 *
 * `out` is the folder the copies sit in, and `say` receives each line of the report. The command
 * passes this plugin's own templates folder; a case passes folders of its own.
 */
export function exportTemplates(book: string, out: string, write: boolean, say: (line: string) => void = console.log): number {
  if (!book || !existsSync(join(book, BOOK_TEMPLATES))) {
    // A PARTNER RUNS THIS AND NOTHING HAPPENS, which is correct. They hold the plugin and not the
    // book, so there is nothing to export from — the copies they already have are the answer.
    say("no foundation book here — nothing to export, and the shipped copies stand");
    return 0;
  }

  const index = join(out, COPY_INDEX);
  const names = templatesOf(book).filter((name) => name !== BOOK_INDEX);
  // The book's index is written FIRST, because it is one of the files the copy carries.
  const bookIndex = renderBookIndex(book, names);
  const bookIndexPath = join(book, BOOK_TEMPLATES, BOOK_INDEX);
  const bookIndexStale = !existsSync(bookIndexPath) || readFileSync(bookIndexPath, "utf8") !== bookIndex;
  if (bookIndexStale && write) writeFileSync(bookIndexPath, bookIndex);
  const stale: string[] = [];
  for (const name of names) {
    const from = join(book, BOOK_TEMPLATES, name);
    const to = join(out, name);
    const source = readFileSync(from);
    const current = existsSync(to) ? readFileSync(to) : null;
    if (current !== null && current.equals(source)) continue;
    stale.push(name);
    if (write) {
      mkdirSync(dirname(to), { recursive: true });
      writeFileSync(to, source);
    }
  }

  // A COPY THE BOOK NO LONGER HOLDS. Every file in the copy folder is the book's, except the copy's
  // own index, so a file the book does not name is one the book deleted or renamed.
  const held = new Set(names);
  const extra = filesUnder(out).filter((name) => name !== COPY_INDEX && !held.has(name));
  if (write) {
    for (const name of extra) rmSync(join(out, name), { force: true });
    if (extra.length > 0) removeEmptyFolders(out);
  }

  const copyIndex = renderIndex(book, names);
  const indexStale = !existsSync(index) || readFileSync(index, "utf8") !== copyIndex;
  if (indexStale && write) {
    mkdirSync(out, { recursive: true });
    writeFileSync(index, copyIndex);
  }

  if (write) {
    say(`${names.length} template(s) exported · ${stale.length} rewritten · ${extra.length} removed · index ${indexStale ? "rewritten" : "current"}`);
    return 0;
  }

  if (!stale.length && !extra.length && !indexStale && !bookIndexStale) {
    say(`${names.length} template(s) · every copy current`);
    return 0;
  }
  say(`${stale.length} template(s) behind the book${indexStale ? ", and the index too" : ""}:`);
  for (const name of stale) say(`  ${name}`);
  if (extra.length > 0) {
    say(`${extra.length} cop${extra.length === 1 ? "y" : "ies"} the book no longer holds:`);
    for (const name of extra) say(`  ${name}`);
  }
  say("  run `spn-devex restates files write <book>`");
  return 1;
}

/** Both actions are one comparison of the book's templates with this plugin's copies; `write` is the one that changes files. */
const run = (args: string[], write: boolean): number =>
  exportTemplates(onePath(scopeOf(readWords(args).paths, REQUIRED)), OUT, write);

export const actions: Record<string, Action> = {
  check: {
    describe: "report each copy that is behind the book or that the book no longer holds, and write nothing",
    usage: "<book>",
    run: (args) => run(args, false),
  },
  write: {
    describe: "copy the book's templates into this plugin, and remove each copy the book no longer holds",
    usage: "<book>",
    run: (args) => run(args, true),
  },
};
